[book]
authors = ["NilPointer Software"]
language = "en"
multilingual = false
src = "src"
title = "Bot Designer for Discord - Wiki"
[output.html]
theme = "src/theme"
default-theme = "bdfd"
preferred-dark-theme = "bdfd"
