name: Wiki Deploy

on:
  push:
    branches:
      - prerelease
      - master

jobs:
  build:
    name: Build wiki book
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Build book
      run: mdbook build
    - name: Upload book
      uses: actions/upload-artifact@v3
      with:
        name: book
        path: book

  deploy-stable:
    name: Deploy stable wiki
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Prepare to fetch book
      run: |
        mv nightly ..
        rm -rf *
    - name: Fetch book artifact
      uses: actions/download-artifact@v3
      with:
        name: book
    - name: Deploy
      run: |
        mv ../nightly .
        git config user.name "Github Actions"
        git config user.email ""
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
    - name: Send wiki update notification
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.WEBHOOK }}
      with:
        args: "Stable Wiki update!\n```${{ github.event.head_commit.message }}``` by ${{ github.event.head_commit.author.username }}"

  deploy-nightly:
    name: Deploy nightly wiki
    needs: build
    if: github.ref == 'refs/heads/prerelease'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Prepare to fetch book
      run: |
        rm -rf nightly/*
    - name: Fetch book artifact
      uses: actions/download-artifact@v3
      with:
        name: book
        path: nightly
    - name: Deploy
      run: |
        git config user.name "Github Actions"
        git config user.email ""
        git add .
        git commit -m "Deploy nightly $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
    - name: Send wiki update notification
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.WEBHOOK }}
      with:
        args: "Nightly Wiki update!\n```${{ github.event.head_commit.message }}``` by ${{ github.event.head_commit.author.username }}"
